Fix 'LAYER' keyword when writting a track
The-OpenROAD-Project/def pull request #5
Opened 2020-02-22 17:09 UTC by christosg88

According to the DEF syntax reference, the LAYER keyword is optional.

Up to this point we were writing the LAYER keyword even when the track had no
specified layers.

This lead to parsing errors when reading a DEF that for some tracks no LAYER wa
specified.

2020-02-25 16:02 UTC, jjcherry56 requested changes
the change looks reasonable but it has to merge to the openroad branch.
master is a checkpoint, not development

2020-02-25 16:43 UTC, christosg88 commented
> 
> the change looks reasonable but it has to merge to the openroad branch.
> master is a checkpoint, not development

I don't see any "openroad" branch, just "master".
Is it maybe a private branch?
Or are you talking about a different repository?

2020-02-25 20:55 UTC, jjcherry56 commented
you're right, I thought this was a different repo. master is the correct branch.
what code is using this repo to write def? opendb does not.

2020-02-25 20:58 UTC, jjcherry56 approved these changes

2020-02-25 21:21 UTC, christosg88 commented
I don't which projects  use this code, but I use it in a private repository to test some legalization algorithms, and I forked this one for the def parser.
Since it's more difficult to contribute to the Si2 project, I use this one as a submodule and contribute here any changes I make for stability.

2020-02-25 21:26 UTC, jjcherry56 commented
So I think you recognize that any changes could be lost if/when the repo is
updated to a newer Si2 release.

On Tue, Feb 25, 2020 at 1:21 PM Christos Gantidis <notifications@github.com>
wrote:

> I don't which projects use this code, but I use it in a private repository
> to test some legalization algorithms, and I forked this one for the def
> parser.
> Since it's more difficult to contribute to the Si2 project, I use this one
> as a submodule and contribute here any changes I make for stability.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/def/pull/5?email_source=notifications&email_token=AIJDZFLUW2V4N2L3UURZ5A3REWDV3A5CNFSM4KZTBAP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5RQBI#issuecomment-591075333>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIJDZFMOKNTQCUX6YOXUVQTREWDV3ANCNFSM4KZTBAPQ>
> .
>

2020-02-25 21:29 UTC, christosg88 commented
Yeah I know, but that's life.
I have my fork so if that happens I can merge my changes back to the newer version.
Until then, since Si2 made it so difficult to contribute, I am fine making changes here in case anyone else uses this repository.

2020-02-25 21:42 UTC, christosg88 commented
BTW I see that also RePlace is also using this repository as a submodule.

2020-02-25 22:58 UTC, jjcherry56 commented
Replace only uses the def submodule on an obsolete branch that predates the
openroad integration.

On Tue, Feb 25, 2020 at 1:42 PM Christos Gantidis <notifications@github.com>
wrote:

> BTW I see that also RePlace is also using this repository as a submodule.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/The-OpenROAD-Project/def/pull/5?email_source=notifications&email_token=AIJDZFMHMWGQJOXJ272BOJTREWGERA5CNFSM4KZTBAP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5TX7Y#issuecomment-591084543>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIJDZFIE44W36BIQH3BCB5TREWGERANCNFSM4KZTBAPQ>
> .
>

2020-03-27 01:41 UTC, jjcherry56 commented
ah, nobody is going actually merge this and delete the branch. that is your job.

2020-04-05 11:50 UTC, christosg88 commented
Sorry for the late response. I don't have write permissions to this repository. I see that the changes have been approved but I cannot push to the upstream (this repo) the merged commit from origin (my fork), I get the following error:
```
ERROR: Permission to The-OpenROAD-Project/def.git denied to christosg88.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2020-04-05 15:24 UTC, merged